<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="profile-img">
                <img alt="Me" src="/img/layout/pict-mbuonomo.jpg">
            </div>
            <div class="profile-info">
                <h2>Mike Buonomo</h2>
                <h4>Software Developer</h4>
                <small>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form Ipsum available.</small>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <ul class="timeline">
        <li>
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
            <div>What I did</div>
        </li>
        <li>
            <i class="fa fa-building" aria-hidden="true"></i>
            <div>What I did</div>
        </li>
        <li>
            <i class="fa fa-graduation-cap" aria-hidden="true"></i>
            <div>What I did</div>
        </li>
    </ul>
</div>
