<link href="/css/timeline.css" media="screen" rel="stylesheet" type="text/css">
<div class="container">
    <div class="row">
        <div class="col-sm-7">
            <div class="profile-info">
                <div class="profile-img">
                    <img alt="Me" src="/img/layout/pict-mbuonomo.jpg">
                </div>
                <h2>Mike Buonomo</h2>
                <h4>Software Developer</h4>
                <small>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form Ipsum available. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form Ipsum available.</small>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="profile-about">
                <table class="custom-list">
                    <tr>
                        <td><i class="fa fa-map-marker fa-fw" aria-hidden="true"></i></td>
                        <td>Hazlet, New Jersey, USA</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-envelope fa-fw" aria-hidden="true"></i></td>
                        <td><a href="mailto:mike@buonomo.net">mike@buonomo.net</a></td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-file-text fa-fw" aria-hidden="true"></i></td>
                        <td>Click <a href="#">here</a> to download my resume</td>
                    </tr>
                    <tr>
                        <td><i class="fa fa-beer fa-fw" aria-hidden="true"></i></td>
                        <td>I love IPAs</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div id="vertical-timeline" class="vertical-container light-timeline center-orientation">

                <div class="vertical-timeline-block">
                    <div class="vertical-timeline-icon blue-bg">
                        <i class="fa fa-briefcase"></i>
                    </div>

                    <div class="vertical-timeline-content">
                        <h1 class="vertical-title">
                            CareerCo<br/>
                            <small>Septemer 7, 2014 - Now</small>
                        </h1>
                        <h2>Software Developer</h2>
                        <table class="custom-list sm-list">
                            <tr>
                                <td><i class="fa fa-map-marker fa-fw" aria-hidden="true"></i></td>
                                <td>
                                    1200 South Ave, Suite 202<br/>
                                    Staten Island, New York, 10314
                                </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-info-circle fa-fw" aria-hidden="true"></i></td>
                                <td>CareerCo is a small company which finds candidates for a range of job and education clients.</td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-laptop fa-fw" aria-hidden="true"></i></td>
                                <td>PHP, JavaScript (JQuery), HTML5, CSS3, MySQL, MongoDB, Elasticsearch</td>
                            </tr>
                        </table>
                        <h3>Responsibilities and Projects</h3>
                        <ul>
                            <li>Develope and maintain internal admin sites which allow detailed customization and rapid deployment of new configurations for our site's results pages.</li>
                            <li>Built and maintain our E3 website which allows our clients access their candidate information, generate and download reports, invoices, and more.</li>
                            <li>Write and maintain a large number of scripts which allow us to send candidate information to our clients in real time usually using the RESTful API.</li>
                            <li>Maintain and create scripts to upload call recordings from our callcenters to our clients in real time and in batches.</li>
                        </ul>
                        <span class="vertical-date">
                            CareerCo <br>
                            <small>Septemer 7, 2014 - Now</small>
                        </span>
                    </div>
                </div>

                <div class="vertical-timeline-block">
                    <div class="vertical-timeline-icon green-bg">
                        <i class="fa fa-university"></i>
                    </div>

                    <div class="vertical-timeline-content">
                        <h1 class="vertical-title">
                            William Paterson University<br/>
                            <small>Graduated May 2014</small>
                        </h1>
                        <h2>Student</h2>
                        <table class="custom-list sm-list">
                            <tr>
                                <td><i class="fa fa-map-marker fa-fw" aria-hidden="true"></i></td>
                                <td>
                                    300 Pompton Road<br/>
                                    Wayne, New Jersey 07470
                                </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-graduation-cap fa-fw" aria-hidden="true"></i></td>
                                <td>Bachelor of Science, Computer Science</td>
                            </tr>
                        </table>
                        <h3>Projects and Achievements</h3>
                        <ul>
                            <li>Built a static website for my wonderful mother <a href="http://www.keyhomesolutions.net">KeyHomeSolutions</a></li>
                            <li>Used a RaspberryPi as a LAMP server to originally host this website</li>
                            <li>Asked to present my website for the annual Computer Science Advisory Board Meeting at William Paterson University in 2014</li>
                            <li>Built a calcutalor app for Android</li>
                        </ul>
                        <span class="vertical-date">
                            William Paterson University <br>
                            <small>Graduated May 2014</small>
                        </span>
                    </div>
                </div>

                <div class="vertical-timeline-block">
                    <div class="vertical-timeline-icon red-bg">
                        <i class="fa fa-briefcase"></i>
                    </div>

                    <div class="vertical-timeline-content">
                        <h1 class="vertical-title">
                            Royal Communications Consultants (internship)<br/>
                            <small>May, 2013 - December 2013</small>
                        </h1>
                        <h2>Jr. Datacenter Technician</h2>
                        <table class="custom-list sm-list">
                            <tr>
                                <td><i class="fa fa-map-marker fa-fw" aria-hidden="true"></i></td>
                                <td>
                                    39 Broadway, Suite 3030<br/>
                                    New York, New York, 10006
                                </td>
                            </tr>
                            <tr>
                                <td><i class="fa fa-info-circle fa-fw" aria-hidden="true"></i></td>
                                <td>RCC is a full service IT firm which provides solutions for the development and support of IT infrastructure.</td>
                            </tr>
                        </table>
                        <h3>Tasks</h3>
                        <ul>
                            <li>Installed/decommissioned servers and network devices</li>
                            <li>Worked in datacenters owned by large companies such as J.P. Morgan</li>
                            <li>A lot of cable patching</li>
                        </ul>
                        <span class="vertical-date">
                            Royal Communications Consultants (internship) <br>
                            <small>May, 2013 - December 2013</small>
                        </span>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
