<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php if ($this->route->request->parts['path'] != '/'): ?><?php echo $this->route->controller ?> | <?php endif ?>Mike Buonomo</title>
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/styles.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/<?php echo strtolower($this->route->controller) ?>.css" media="screen" rel="stylesheet" type="text/css">
    <script src="/js/jquery-1.12.3.min.js" type="text/javascript"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/functions.js" type="text/javascript"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img alt="Brand" src="/img/layout/pict-mbuonomo.jpg" class="brand-logo">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
<!--                 <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">SendMeJokes</a></li>
                            <li><a href="#">Helpful Scripts</a></li>
                            <li><a href="#">MiniMVC</a></li>
                        </ul>
                    </li>
                </ul> -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="link-icon-li">
                        <a href="https://www.linkedin.com/in/mikebuonomo" class="link-icon-a">
                            <i class="fa fa-linkedin-square link-icon"></i>
                        </a>
                    </li>
                    <li class="link-icon-li">
                        <a href="https://github.com/mrb2590" class="link-icon-a">
                            <i class="fa fa-github-square link-icon"></i>
                        </a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main">
        <?php $this->content() ?>
    </div>
</body>
</html>
